name: Android CI

on:
  push:
    branches: [ dragon-egg.ofuton ]
  pull_request:
    branches: [ dragon-egg.ofuton ]
  workflow_dispatch:
    branches: [ dragon-egg.ofuton ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate twitter.properties
      run: echo '${{secrets.TWITTER_CS}}'$'\n''${{secrets.TWITTER_CK}}' >> ./app/twitter.properties
    - name: Build with Gradle
      run: ./gradlew assembleDebug -x lint --no-daemon

